---
title: "Melanoma BCR repertoire analysis"
author: "Anna Obraztsova"
date: '1 June 2017'
output: pdf_document
---

```{r, fig.height=8, message=FALSE}
library(dplyr)
library(ggplot2)
library(reshape2)
library(plyr)

load('clones.rda')
codes <- read.table('SKCM-codes-samples-for-patients-tss.txt', header=F, sep="\t")
colnames(codes) <- c('patient_id', 'c1', 'c2', 'c3', 'tissue')
clones <- merge(clones, codes)
clones$tissue <- revalue(clones$tissue, c("Distant Metastasis" = "DistMet",
                                          "Primary Tumor" = "PrTumor",
                                          "Regional Cutaneous or Subcutaneous Tissue (includes satellite and in-transit metastasis)" = "Regional", "Regional Lymph Node" = "LNode"))
clones$LN <- ifelse(clones$tissue == "LNode", 'LNode', 'Other')

c <- clones %>% group_by(patient_id, tissue) %>%
  dplyr::summarise(trees = n(), nodes = sum(nodes), mean.diameter = mean(diameter),
                   max.tree = max(nodes)) %>%
  dplyr::select(tissue, patient_id, trees, nodes, mean.diameter, max.tree) %>%
  melt(id.vars = c('tissue', 'patient_id'))

ggplot(c, aes(x = tissue, y = value)) + 
  geom_boxplot() +
  facet_wrap(~variable, scales="free_y") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r, fig.height=6, fig.width=4}
c1 <- clones %>% group_by(patient_id, LN) %>%
  dplyr::summarise(trees = n(), nodes = sum(nodes), mean.diameter = mean(diameter),
                   max.tree = max(nodes)) %>%
  dplyr::select(LN, patient_id, trees, nodes, mean.diameter, max.tree)

ggplot(melt(c1, id.vars = c('LN', 'patient_id')), aes(x = LN, y = value)) + 
  geom_boxplot() +
  facet_wrap(~variable, scales="free_y") +
  theme_bw()

for (i in c('trees', 'nodes', 'mean.diameter', 'max.tree')){
  cat(i, 't-Test p-value\n', t.test(c1[[i]] ~ c1[['LN']])$p.value, '\n')
}
```

```{r, fig.height=4, fig.width=3, }
library(tidyr)
library(reshape2)

load('shm.rda')

s <- data.frame(mut.type = unlist(cdr3.shm$mut.type), position = unlist(cdr3.shm$position),
                  cdr3.mut = unlist(cdr3.shm$cdr3.muts), aa.from = unlist(cdr3.shm$n1.aa),
                  aa.to = unlist(cdr3.shm$n2.aa), 
                patient_id = rep(cdr3.shm$patient_id, pmax(cdr3.shm$mut.num, 1))) %>%
  filter(!is.na(aa.to)) %>%
  merge(codes) %>%
  mutate( LN = ifelse(tissue == "Regional Lymph Node", 'LNode', 'Other'))

s1 <- s %>% group_by(patient_id, LN, mut.type) %>%
  dplyr::summarise(n = n()) %>%
  dcast(patient_id + LN ~ mut.type, value.var = "n") %>%
  mutate(RS_ratio = R/S)

ggplot(s1, aes(x = LN, y = RS_ratio)) + geom_boxplot()

print(t.test(s1$RS_ratio ~ s1$LN)$p.value)
```

