---
title: "Network analysis"
author: "Mikhail Shugay, Anna Obraztsova"
date: "15/11/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE, fig.height=2, fig.width=2, fig.show = 'hold'}
library(reshape2)
library(ggplot2)
library(dplyr)

df <- read.table('data/graph_stats/graph_summary.txt', head=TRUE)
df.2 <- melt(df, id.vars = c('proj', 'sample'))

ggplot(filter(df.2, variable=='clustering.coeff'), aes(x=proj, group=proj, y=value)) + geom_boxplot() + ggtitle('Clustering coefficient') + theme(plot.title = element_text(size = 10))
ggplot(filter(df.2, variable=='net.diam'), aes(x=proj, group=proj, y=value)) + geom_boxplot() + ggtitle('Network diameter') + theme(plot.title = element_text(size = 10))
ggplot(filter(df.2, variable=='shortest.paths'), aes(x=proj, group=proj, y=value)) + geom_boxplot() + ggtitle('Shortest paths') + theme(plot.title = element_text(size = 10))
```


```{r, warning=FALSE, message=FALSE, fig.height=2, fig.width=2, fig.show = 'hold'}
ggplot(filter(df.2, variable=='char.path.len'), aes(x=proj, group=proj, y=value)) + geom_boxplot() + ggtitle('Characteristic path length') + theme(plot.title = element_text(size = 10))
ggplot(filter(df.2, variable=='avg.num.neighb'), aes(x=proj, group=proj, y=value)) + geom_boxplot() + ggtitle('Average number of neighbours') + theme(plot.title = element_text(size = 10))
ggplot(filter(df.2, variable=='n'), aes(x=proj, group=proj, y=value)) + geom_boxplot() + ggtitle('Number of nodes') + theme(plot.title = element_text(size = 10))
```